name = "CryptoMiniSat"
uuid = "8e9d5576-ec03-11e9-187e-e534548435ab"
authors = ["Laurent Bartholdi <laurent.bartholdi@gmail.com>"]
version = "0.2.1"

[deps]
CryptoMiniSat_jll = "cf02a7a8-8cd0-5932-97be-477f95a4d9ce"

[compat]
CryptoMiniSat_jll = "5.8 - 5.9"
julia = "1.6 - 1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
